Jollix 0.1.1 LiveCD Boot Optionen ---------------- [F1] Startbildschirm anzeigen

Boot Options

1. Keyboard and language selection

Default system and keymap language: german (lang=de).
At the bootprompt type "jollix lang=us" to choose us keymap and english
system language (without "").                                                                                                                                                        

2. ATI Options

To play Half-Life/HL-Mods with an ATI graphics adapter:                         At the bootprompt type "jollix atigamer" (without ""). 

