#!/bin/sh
#            ### create-cloop ###
#
#  This script builds a compressed loopback archive (cloop),
#  that contains the jollix system.
#  Use as root from cvsroot/jollix directory 

# hackattack! Avoids checkfs error on startup.
# Be aware of what you're doing else when date is set 
# do this value and create-cloop is running!
date 010100002005

source skripte/settings
install -d looproot
dd if=/dev/zero of=livecd.loop bs=1k count=1500000
mke2fs -F -q livecd.loop
mount -t ext2 -o loop livecd.loop looproot 
cp -dR ${JOLLIX_DIR}/* looproot --preserve=mode --preserve=ownership 
#cp -dpR ${JOLLIX_DIR}/* looproot
umount looproot
cat livecd.loop | ${CLOOP_DIR}/create_compressed_ucl_fs - 131072 > ${LIVECD_DIR}/livecd.cloop
rm -rf looproot livecd.loop

