#!/bin/sh
# Moduleloader
# Copyright 2003 jollix
# Jochen Spang <knochestolle@web.de>
# Oliver Schwinn <patteh@web.de> 
# location in cloop: /sbin/modules-jollix
# Distributed under the terms of the GNU General Public License, v2 or later

# load all modules
for module in $(pcimodules) ; do
       modprobe -s -k "$module"
done

# if nVidia GK, remove agpgart 
#for module in $(lsmod) ; do
#  if [ "$module" = "NVdriver" ] ; then
#   rmmod agpgart
#  fi 
#done

nvidiafound=0
for module in $(lsmod) ; do
  if [ "$module" = "NVdriver" ] ; then
   nvidiafound=1
  fi
done

if [ $nvidiafound = 0 ] ; then
  cp /etc/X11/XF86Config-vesa /etc/X11/XF86Config
   else
     cp /etc/X11/XF86Config-nvidia /etc/X11/XF86Config
fi



for module in $(lsmod) ; do
  if [ "$module" = "snd" ] ; then
   modprobe snd-pcm-oss
  fi
done

#for module in $(lsmod) ; do
#  if [ "$module" = "usbcore" ] ; then
#   modprobe hid
#  fi
#done

#Alsa unmuten
amixer set Master 100 unmute
amixer set PCM 100 unmute

# USB PS/2 mouse configuration
# wait 5 sec. for usb/devices to be created (hackattack!)

raushier=true
declare -i counter=0
while $raushier ; do
 if grep -i "mouse" /proc/bus/usb/devices >/dev/null
  then
   raushier=false 
  else
   counter=${counter}+1
   echo -n .
   sleep 1 
 fi
 if [ $counter = 5 ]
  then
   raushier=false
 fi
done

if grep -i "mouse" /proc/bus/usb/devices >/dev/null 
 then 
  sed -i -e 's/psaux/input\/mice/' /etc/X11/XF86Config
else
  sed -i -e 's/input\/mice/psaux/' /etc/X11/XF86Config  
fi
