#!/bin/sh
# Moduleloader
# Copyright 2003 jollix
# Jochen Spang <knochestolle@web.de>
# Oliver Schwinn <patteh@web.de> 
# location in cloop: /sbin/modules-jollix
# Distributed under the terms of the GNU General Public License, v2 or later

# load all modules
for module in $(pcimodules) ; do
    modprobe -s -k "$module"
done

# GRAPHIC SECTION ################################################
# graphic adapter module: 0=VESA, 1=NVIDIA, 2=FGLRX
gfxmodule=0

# test nvidia module
modprobe -q nvidia
for module in $(lsmod) ; do
    if [ "$module" = "nvidia" ] ; then
	gfxmodule=1
    fi
done

# test fglrx module
if [ ! $gfxmodule ] ; then
    modprobe -q fglrx
    for module in $(lsmod) ; do
	if [ "$module" = "fglrx" ] ; then
	    gfxmodule=2
	fi
    done
fi

case  $gfxmodule in
    0) # use vesa safemode
	cp /etc/X11/XF86Config-vesa /etc/X11/XF86Config
	opengl-update xfree
	;;
    1) # switch to nvidia
	cp /etc/X11/XF86Config-nvidia /etc/X11/XF86Config
	opengl-update nvidia
	;;
    2) # switch to ati
	cp /etc/X11/XF86Config-ati /etc/X11/XF86Config
	opengl-update ati
	;;
esac


# SOUND SECTION #####################################################
# load oss
for module in $(lsmod) ; do
  if [ "$module" = "snd" ] ; then
   modprobe snd-pcm-oss
  fi
done

# unmute alsa
amixer set Master 25 unmute
amixer set PCM 25 unmute

# USB PS/2 MOUSE SECTION #########################################
# wait 5 sec. for usb/devices to be created (hackattack!)
goon=true
declare -i counter=0
while $goon ; do
    if grep -i "mouse" /proc/bus/usb/devices >/dev/null
	then
	goon=false 
    else
	counter=${counter}+1
	echo -n .
	sleep 1 
    fi
    if [ $counter = 5 ]
	then
	goon=false
    fi
done

if grep -i "mouse" /proc/bus/usb/devices >/dev/null 
    then 
    sed -i -e 's/psaux/input\/mice/' /etc/X11/XF86Config
else
    sed -i -e 's/input\/mice/psaux/' /etc/X11/XF86Config  
fi
