#!/bin/sh
# Moduleloader
# Copyright 2003 jollix
# Jochen Spang <knochestolle@web.de>
# Oliver Schwinn <patteh@web.de> 
# Distributed under the terms of the GNU General Public License, v2 or later

#alle Module laden
for module in $(pcimodules) ; do
       modprobe -s -k "$module"
done

#nVidia GK vorhanden, dann agpgart entfernen
for module in $(lsmod) ; do
  if [ "$module" = "NVdriver" ] ; then
   rmmod agpgart
  fi 
done

for module in $(lsmod) ; do
  if [ "$module" = "snd" ] ; then
   modprobe snd-pcm-oss
  fi
done

for module in $(lsmod) ; do
  if [ "$module" = "usbcore" ] ; then
   modprobe hid
  fi
done

#Alsa unmuten
amixer set Master 100 unmute
amixer set PCM 100 unmute

#USB PS/2 Maus Konfiguration

#Warten bis usb/devices angelegt ist

raushier=true
declare -i counter=0
while $raushier ; do
 if grep -i "mouse" /proc/bus/usb/devices >/dev/null
  then
   raushier=false 
  else
   counter=${counter}+1
   echo -n .
   sleep 1 
 fi
 if [ $counter = 5 ]
  then
   raushier=false
 fi
done

if grep -i "mouse" /proc/bus/usb/devices >/dev/null 
 then 
  sed -ie 's/psaux/input\/mice/' /etc/X11/XF86Config
else
  sed -ie 's/input\/mice/psaux/' /etc/X11/XF86Config  
fi
